apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- deployment.yaml
- service.yaml
- secretproviderclass.yaml
- sa.yaml
- https://github.com/cert-manager/cert-manager/releases/download/v1.17.0/cert-manager.yaml
- issuer.yaml

images:
  - name: quest-image
    newName: 992382391803.dkr.ecr.ap-south-1.amazonaws.com/myecr/rearc-quest
    newTag: 352caa22ebd4c63871dd7fb287a5567786778541