apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- secretproviderclass.yaml
- sa.yaml

images:
  - name: quest-image
    newName: 992382391803.dkr.ecr.ap-south-1.amazonaws.com/myecr/rearc-quest
    newTag: 4c3d0ef875a65d650dae0d61b92ecef7054b85da