apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: quest-deployment-pod-identity-aws-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "quest-secret"
        objectType: "secretsmanager"
        jmesPath:
          - path: SECRET_WORD
            objectAlias: my-secret-word
    usePodIdentity: "true"
  secretObjects:
    - secretName: secret-from-secret-manager
      type: Opaque
      data: 
        - objectName: quest-secret
          key: SECRET_WORD
