apiVersion: v1
kind: Service
metadata:
  name: rearc-quest
  namespace: default
spec:
  selector:
    app: rearc-quest  
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 3000    
  type: ClusterIP      
