name: Build, Push, Deploy
on:
  push:
    branches: [ main ]
    paths:
      - 'quest/**'
  workflow_dispatch:
jobs:
  build-image:
    name: Build and Push Image to Registry
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Print the SHA
        run: |
          echo "${GITHUB_SHA}"
      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ECR_REPO }}
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Build and push Docker image 
        uses: docker/build-push-action@v5
        with:
          context: quest
          file: quest/Dockerfile.test
          push: true
          tags: ${{ secrets.ECR_REPO }}/myecr/rearc-quest:${{ github.sha }}
      - name: Change the tag
        run: |
          sed -i "s/\(newTag: \).*/\1${GITHUB_SHA}/" k8s/quest-kustomize/kustomization.yaml
          cat k8s/quest-kustomize/kustomization.yaml
      - name: Update the image tag for ArgoCD
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: 'k8s/quest-kustomize/kustomization.yaml'
          message: 'Changed the Image Tag to ${GITHUB_SHA}'

      